import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { menuHome } from "src/utils";
import { Footer } from "pages/footer";

const Home: NextPage = React.memo(() => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ZNHK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>ZNHK Project</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          {menuHome?.map((item, index) => {
            return (
              <a key={index} href={item?.href} className={styles.card}>
                <h2>{item?.name} &rarr;</h2>
                <p>{item?.desc}</p>
              </a>
            );
          })}
        </div>
      </main>

      <Footer />
    </div>
  );
});

export default Home;
